import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const apiDir = path.join(root, 'src/api');
const files = fs.readdirSync(apiDir).filter(x => x.endsWith('.js')).sort();
const routes = new Map();
const re = /app\.(get|post|put|patch|delete)\(\s*['"]([^'"]+)['"]/g;
for (const file of files) {
  const text = fs.readFileSync(path.join(apiDir, file), 'utf8');
  for (const m of text.matchAll(re)) {
    const method = m[1].toLowerCase();
    const route = m[2];
    const normalized = route.replace(/:([A-Za-z0-9_]+)/g, '{$1}').replace(/\/\*$/, '/{path}');
    if (!routes.has(normalized)) routes.set(normalized, {});
    routes.get(normalized)[method] = {
      operationId: `${file.replace(/-api\.js$/, '').replace(/-/g, '_')}_${method}_${route.replace(/[^A-Za-z0-9]+/g, '_').replace(/^_|_$/g, '')}`,
      summary: `${method.toUpperCase()} ${route}`,
      responses: {
        '200': { description: 'Successful CloudMail response' },
        '400': { description: 'Invalid request' },
        '401': { description: 'Authentication required or expired' },
        '403': { description: 'Permission denied' },
        '500': { description: 'Server error' }
      }
    };
    const params = [...normalized.matchAll(/\{([^}]+)\}/g)].map(x => ({ name: x[1], in: 'path', required: true, schema: { type: 'string' } }));
    if (params.length) routes.get(normalized)[method].parameters = params;
  }
}
const publicRoutes = new Set(['/login','/refresh','/register','/health','/init','/init/{secret}','/setting/websiteConfig','/oauth/linuxDo/state','/oauth/linuxDo/login','/webhooks']);
for (const [route, methods] of routes) {
  for (const op of Object.values(methods)) if (!publicRoutes.has(route)) op.security = [{ webSession: [] }, { bearerAuth: [] }];
}
const doc = {
  openapi: '3.1.0',
  info: {
    title: 'CloudMail API',
    version: '1.0.0',
    description: 'Versioned CloudMail API contract. /api remains a compatibility alias for Cloud-Mail 3.0.0 clients; /api/v1 is the stable v1 namespace.'
  },
  servers: [
    { url: '/api/v1', description: 'Stable v1 API' },
    { url: '/api', description: 'Legacy compatibility alias' }
  ],
  paths: Object.fromEntries([...routes.entries()].sort(([a],[b]) => a.localeCompare(b))),
  components: { securitySchemes: {
    webSession: { type: 'apiKey', in: 'cookie', name: '__Host-cfmail_session' },
    bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' }
  }}
};
const json = JSON.stringify(doc, null, 2) + '\n';
fs.writeFileSync(path.join(root, 'openapi/cloudmail-v1.openapi.json'), json);
fs.writeFileSync(path.join(root, 'src/openapi/openapi-document.js'), `// Generated by scripts/generate-openapi.mjs. Do not edit by hand.\nexport default ${JSON.stringify(doc, null, 2)};\n`);
console.log(`Generated OpenAPI with ${routes.size} paths / ${[...routes.values()].reduce((n,x)=>n+Object.keys(x).length,0)} operations`);
